### ISSUE TITLE
data: singular or plural?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#147] opened 2019-09-30 21:39 UTC
decide so that we all do this consistently throughout!

**Comment by bbdaniels** [comment] 2019-10-01 14:17
Weirdly the correct answer is to be inconsistent, and change it depending on the use case:

<img width="513" alt="Screen Shot 2019-10-01 at 10 16 56 AM" src="https://user-images.githubusercontent.com/1459122/65970455-9b830c80-e434-11e9-8a10-61838813820f.png">

**Comment by luizaandrade** [comment] 2020-02-18 21:46
I think we can defer to the DIME style guide for this as in #295 and close this one?

**Comment by bbdaniels** [comment] 2020-02-18 21:57
Yes, close

**Comment by kbjarkefur** [comment] 2020-02-18 23:20
Agree. Closing as it is a duplicate of #295 and the other issue includes more

**Closed by kbjarkefur** 2020-02-18 23:20 UTC
Labels: final review
