### ISSUE TITLE
Update on data encryption

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#75] opened 2019-08-05 23:49 UTC
From @dc-coder:

The second comment is about data encryption. Here is one of the section on page 55.

> Encryption in cloud storage, by contrast, is not enabled by default. This is because the service will not encrypt user data unless you confirm you know how to operate the encryption system and understand the consequences if basic protocols are not followed. 

This is not true for AWS and Azure anymore (maybe it was true at the time of writing). I just thought to give you a hint in case you are planning on re-publishing.

----------
AWS
https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html

Server-side encryption is about data encryption at rest—that is, Amazon S3 encrypts your data at the object level as it writes it to disks in its data centers and decrypts it for you when you access it. As long as you authenticate your request and you have access permissions, there is no difference in the way you access encrypted or unencrypted objects. For example, if you share your objects using a presigned URL, that URL works the same way for both encrypted and unencrypted objects.

Use Server-Side Encryption with Amazon S3-Managed Keys (SSE-S3) – Each object is encrypted with a unique key. As an additional safeguard, it encrypts the key itself with a master key that it regularly rotates. Amazon S3 server-side encryption uses one of the strongest block ciphers available, 256-bit Advanced Encryption Standard (AES-256), to encrypt your data. For more information, see Protecting Data Using Server-Side Encryption with Amazon S3-Managed Encryption Keys (SSE-S3).

Azure
https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption

Azure Storage automatically encrypts your data when persisting it to the cloud. Encryption protects your data and to help you to meet your organizational security and compliance commitments. Data in Azure Storage is encrypted and decrypted transparently using 256-bit AES encryption, one of the strongest block ciphers available, and is FIPS 140-2 compliant. Azure Storage encryption is similar to BitLocker encryption on Windows.

Azure Storage encryption is enabled for all new and existing storage accounts and cannot be disabled. Because your data is secured by default, you don't need to modify your code or applications to take advantage of Azure Storage encryption.

**Comment by kbjarkefur** [comment] 2019-08-06 08:28
Good point. I guess we should say that cloud storage is not always enabled for the reasons we are mentioning, so researchers should not assume that the data is encrypted in the cloud until they can confirm that. So they should assume that encryption is not enabled until they get confirmed that it is.

SurveyCTO store their data in S3 buckets so based on this comment it is encrypted. But that only means that it is encrypted to Amazon and anyone hacking the S3 bucket. SurveyCTO does still have the key to that encryption so it is not encrypted for them. So I guess the main point is that the research team should make sure their data is encrypted in a way where they only have access to the key.

**Comment by dc-coder** [comment] 2019-08-06 20:48
@kbjarkefur yeah i guess you are right. it is worth mentioning that there are different encryption methods for cloud providers and that at times the cloud provider can manage the keys and processes for the user. people should check stuff up and not assume that encryption is enabled by default.

What would be nice to add maybe, and this is a giant maybe, is that now cloud providers make it easier to encrypt/decrypt data on the fly, without the need to change any software. This might encourage people to be less worried about encryption. I honestly would be terrified of loosing keys ;p especially after like 5 years.

AWS
> As long as you authenticate your request and you have access permissions, there is no difference in the way you access encrypted or unencrypted objects.

Azure
> Because your data is secured by default, you don't need to modify your code or applications to take advantage of Azure Storage encryption.

**Comment by mariaruth** [comment] 2020-01-14 16:10
@kbjarkefur i don't fully understand what "now cloud providers make it easier to encrypt/decrypt data on the fly, without the need to change any software" means. is this worth mentioning?

**Comment by kbjarkefur** [comment] 2020-02-07 14:14
It is related to "DropBox, Microsoft or Amazon can only have the decryption key if they were listed on the IRB". Our rule is that no one **not** listed on the IRB is allowed to have access to the decryption key. 

The encryption they use is super strong, but to happen on the fly they must have access to our key, and while it is nothing wrong with them adding this layer of security as well, it is not compliant with our rules if unless we have a second layer of encryption where only we have the key. It will always come down to only us having the key, and keep it safe, also after 5 years.

This is explained here: https://dimewiki.worldbank.org/wiki/Encryption#Symmetric_Encryption

I am closing as this will not be included in the book.

**Closed by kbjarkefur** 2020-02-07 14:14 UTC
Labels: Ch 5: Collecting Primary Data
