### ISSUE TITLE
Content: Stata style guide

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#35] opened 2019-05-16 20:24 UTC
To discuss:

1. Commenting: when to use *, /**/, //
1. Horizontal spacing
2.1. Columns
2.2. Space before and after operators
2.3. Space before (?) and after commas

**Comment by kbjarkefur** [comment] 2019-05-17 15:38
I have this on my list as well. 

And in addition to style guide, a section on how to read our code.

- How to use `help commandname`
- Which commands we abbreviate and to what:
  - Summarize : su or sum?
  - Tabulate : tab or ta?
  - Regress : reg
  - Generate : gen

**Comment by bbdaniels** [comment] 2019-05-23 17:32
I think I am mostly okay with command abbreviations, although if I could choose I would agree with the recommendation to always use 3 letters for a command unless the command itself is only two letters.

For variable abbreviations I prefer never to use them. I also prefer rarely to allow wildcards in analysis files with the exception of the form `xx_*` since this will be an explicitly constructed set of variables in general. 

Other wildcards like `xx_?_*_xx` can be OK in data construction (particularly with `rename`) since the underlying data structure should be fixed and therefore it will rarely cause unexpected behavior.

**Comment by bbdaniels** [comment] 2019-05-23 17:39
Boolean evaluations should always have parentheses?
ie ```if (`x' == 1)``` NOT ```if `x' == 1```

**Comment by bbdaniels** [comment] 2019-05-23 17:43
`twoway` is the only command I'd allow as `tw` and should be written as `tw (xx)(xx)(xx)`, not `tw xx||xx||xx`

**Comment by bbdaniels** [comment] 2019-05-23 17:44
Globals should be written as `${NAME}`, not `$NAME`

**Comment by bbdaniels** [comment] 2019-05-23 17:45
File paths should be written as `"/path/to/file.dta"', ie, should always include quotations, file extensions, and forward slashes

**Comment by bbdaniels** [comment] 2019-05-23 17:50
The *option comma* should be spaced on either side or start a newline, ie,
`collapse (mean) cpp theta_mle [fweight = weight] , by(state_code) fast`
or 
```
collapse (mean) cpp theta_mle [fweight = weight] 
  , by(state_code) fast
```
NOT
`collapse (mean) cpp theta_mle [fweight = weight], by(state_code) fast`
NOT
```
collapse (mean) cpp theta_mle [fweight = weight] ,
  by(state_code) fast
```

**Comment by bbdaniels** [comment] 2019-05-23 17:51
Also, when there are multiple lines for a single command, the option comma can be at the same indentation level as the main command, such as:
```
graph hbar ///
    invil if (priv == 1) ///
  , over(statename , sort(1) descending ) blabel(bar, format(%9.0f)) ///
    ylab(0 "0%" 25 "25%" 50 "50%" 75 "75%" 100 "100%") ///
    ytit("Share of private primary care visits made in own village")
```

**Comment by bbdaniels** [comment] 2019-05-23 18:05
macro naming: camelCase? (ie, no underscores)
so ``` `aNewVariable' ``` not ``` `a_new_variable' ```

**Comment by bbdaniels** [comment] 2019-05-23 18:16
other things I mostly agree with from https://www.stata-journal.com/sjpdf.html?articlenum=pr0018:

use `!` for NOT, rather than `~`

Put spaces around each binary operator except ^ (`gen z = x + y` is clear,
but `x ^ 2` looks odder than `x^2`).

Except when order of operations applies: 
`hours + minutes/60 + seconds/3600`, NOT `hours + minutes / 60 + seconds / 3600`

Don't use `#delimit` unless you are writing an adofile

Use `///` to continue a line, NOT `/* */`

Avoid `preserve ... restore`: rather reload your data for each section.

Things I disagree with:

Tabs = 8 spaces (I use two spaces only, and never use tabs)

Direct memory management and speed optimization are rare concerns; if your programs hang, you are either working with too big data or have made a serious coding error

Exception: make sure you don't print very much to the results window. This can be accomplished by using `run file.do` rather than `do file.do` in the `master.do` file, or by running things like `reg` with `qui`. NEVER use interactive commands `sum`, `tab`, etc in dofiles, unless they are with `qui` for the purpose of getting `r()`-statistics afterwards

**Comment by bbdaniels** [comment] 2019-05-23 18:28
Long expressions: operator on newline, ie:
```
gen sumvar = x ///
  + y ///
  - z ///
  + a*b - c
```

**Comment by bbdaniels** [comment] 2019-05-23 18:37
good stuff mostly in here, except the last part (filenames): https://hwpi.harvard.edu/files/sdp/files/sdp-toolkit-coding-style-guide.pdf

**Comment by luizaandrade** [comment] 2019-05-23 20:03
> I think I am mostly okay with command abbreviations, although if I could choose I would agree with the recommendation to always use 3 letters for a command unless the command itself is only two letters.
> 
> For variable abbreviations I prefer never to use them. I also prefer rarely to allow wildcards in analysis files with the exception of the form `xx_*` since this will be an explicitly constructed set of variables in general.
> 
> Other wildcards like `xx_?_*_xx` can be OK in data construction (particularly with `rename`) since the underlying data structure should be fixed and therefore it will rarely cause unexpected behavior.

No variables abbreviation, but wildcards are ok, as long as the underlying data is static.

**Comment by luizaandrade** [comment] 2019-05-23 20:04
> File paths should be written as `"/path/to/file.dta"`, ie, should always include quotations, file extensions, and forward slashes
> 
> And should always be absolute file paths unless command syntax makes this impossible

*Absolute* and *dynamic* files paths.

**Comment by kbjarkefur** [comment] 2019-05-23 20:09
> 
> 
> macro naming: camelCase? (ie, no underscores)
> so `` `aNewVariable' `` not `` `a_new_variable' ``
> 
> otherwise, lower case for everything (variables, filenames, etc)
> 
> also, use only [a-z][0-9][-][ _ ] in all names

Explain the differnt file name types. It is not important which you use, as long as your consitent

**Comment by luizaandrade** [comment] 2019-05-23 20:11
> **Things I mostly agree with** from https://www.stata-journal.com/sjpdf.html?articlenum=pr0018:
> 
> use `!` for NOT, rather than `~`
> 
> Put spaces around each binary operator except ^ (`gen z = x + y` is clear,
> but `x ^ 2` looks odder than `x^2`).
> 
> Except when order of operations applies:
> `hours + minutes/60 + seconds/3600`, NOT `hours + minutes / 60 + seconds / 3600`
> 
> Don't use `#delimit` unless you are writing an adofile
> 
> Use `///` to continue a line, NOT `/* */`
> 
> Avoid `preserve ... restore`: rather reload your data for each section.
> 
> **Things I disagree with:**
> 
> Tabs = 8 spaces (I use two spaces only, and never use tabs)
> 
> Direct memory management and speed optimization are rare concerns; if your programs hang, you are either working with too big data or have made a serious coding error
> 
> Exception: make sure you don't print very much to the results window. This can be accomplished by using `run file.do` rather than `do file.do` in the `master.do` file, or by running things like `reg` with `qui`. NEVER use interactive commands `sum`, `tab`, etc in dofiles, unless they are with `qui` for the purpose of getting `r()`-statistics afterwards

For order of operations, use parenthesis.

**Comment by kbjarkefur** [comment] 2019-05-23 20:15
use `compress`

**Comment by kbjarkefur** [comment] 2019-05-23 20:21
Use this:
```
local crops potato tomato banana 
for crop of local crops {

}
```

And NOT this:
```
for i in potato tomato banana {

}
```

**Comment by bbdaniels** [comment] 2019-12-15 02:08
A long one here with perhaps more inspiration: https://github.com/google/styleguide/blob/gh-pages/pyguide.md

**Closed** 2020-02-18 19:39 UTC
Labels: stata
